-- nuttachai_673380581-8_04 owns only the booking/equipment join table.
-- Manual setup for PostgreSQL and H2; this file is not auto-run by Spring Boot.
-- Prerequisites: bookings(id BIGINT) and equipment(id BIGINT) already exist.
-- This script creates neither parent tables nor parent data, and deletes no data.
-- Run schema.sql before data.sql, using an isolated fixture database first.
--
-- Existing installations are upgraded below: required quantity, positive
-- quantity CHECK, and booking/equipment lookup indexes.
-- Stop application writers and back up the database before manual migration.
-- Run PostgreSQL DDL inside a transaction; H2 DDL may auto-commit, so do not
-- assume a failure rolls back earlier statements. Invalid/null quantities
-- fail visibly: this script never repairs or deletes rows.
-- Inspect these conditions before running against an existing table:
--   SELECT * FROM booking_equipment WHERE quantity IS NULL OR quantity <= 0;
-- Existing FK definitions/other columns are left in place; new-table FKs are
-- created here. Full application schema/migrations remain other owners' scope.

CREATE TABLE IF NOT EXISTS booking_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_booking_equipment_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_equipment_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment (id)
);

ALTER TABLE booking_equipment ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE booking_equipment DROP CONSTRAINT IF EXISTS ck_booking_equipment_quantity;
ALTER TABLE booking_equipment ADD CONSTRAINT ck_booking_equipment_quantity CHECK (quantity > 0);

-- Ordinary indexes support booking lookup/deletion and reservation queries
-- joining from equipment_id. The existing service inserts replacement rows
-- before deleting old orphans, so a unique booking/equipment pair would break
-- booking edits. FK deletion remains restricted by the database; the existing
-- JPA aggregate handles removal of a booking's equipment rows.
CREATE INDEX IF NOT EXISTS idx_booking_equipment_booking
    ON booking_equipment (booking_id);

CREATE INDEX IF NOT EXISTS idx_booking_equipment_equipment
    ON booking_equipment (equipment_id);
