-- Member 4: BookingEquipment schema / quantity-and-index upgrade only.
-- For a new application database, use db/postgresql/schema.sql instead.
-- Parent tables bookings and equipment must already exist.
-- PostgreSQL usage: run explicitly in a transaction with ON_ERROR_STOP enabled.
-- Invalid existing quantities stop the upgrade; no rows are deleted or corrected.
-- Existing foreign keys are preserved but are not repaired by this legacy upgrade.
-- Repeated booking/equipment links remain allowed, matching JPA orphan replacement.

CREATE TABLE IF NOT EXISTS booking_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_booking_equipment_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_equipment_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id)
);

ALTER TABLE booking_equipment ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE booking_equipment DROP CONSTRAINT IF EXISTS ck_booking_equipment_quantity;
ALTER TABLE booking_equipment ADD CONSTRAINT ck_booking_equipment_quantity CHECK (quantity > 0);

CREATE INDEX IF NOT EXISTS idx_booking_equipment_booking ON booking_equipment (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_equipment_equipment ON booking_equipment (equipment_id);
