package com.example.roombooking.config;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.sql.SQLException;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class LocalUserTableMigrationTest {
    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    void preservesAccountsForeignKeysAndNextIdentityAcrossTableRename(boolean lowerCase) throws Exception {
        DataSource database = database(lowerCase);
        execute(database,
                "CREATE TABLE \"user\" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(50), password VARCHAR(255))",
                "INSERT INTO \"user\" (username, password) VALUES ('member', 'existing-password-hash')",
                "CREATE TABLE bookings (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES \"user\"(id))",
                "INSERT INTO bookings VALUES (10, 1)",
                "CREATE TABLE user_profile (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES \"user\"(id))",
                "INSERT INTO user_profile VALUES (20, 1)");

        LocalUserTableMigrationConfig.migrate(database);
        LocalUserTableMigrationConfig.migrate(database); // A second startup must be harmless.

        assertEquals(1, number(database, "SELECT COUNT(*) FROM bookings b JOIN users u ON b.user_id=u.id JOIN user_profile p ON p.user_id=u.id WHERE u.username='member' AND u.password='existing-password-hash'"));
        execute(database, "INSERT INTO users (username, password) VALUES ('new-member', 'new-hash')",
                "INSERT INTO bookings VALUES (11, 2)");
        assertEquals(2, number(database, "SELECT id FROM users WHERE username='new-member'"));
        assertThrows(SQLException.class, () -> execute(database, "INSERT INTO bookings VALUES (12, 999)"));
    }

    @Test
    void leavesNewDatabaseForHibernateToCreate() throws Exception {
        DataSource database = database(true);
        LocalUserTableMigrationConfig.migrate(database);
        assertThrows(SQLException.class, () -> number(database, "SELECT COUNT(*) FROM \"users\""));
    }

    @Test
    void preservesAlreadyMigratedAccounts() throws Exception {
        DataSource database = database(true);
        execute(database, "CREATE TABLE users (id BIGINT PRIMARY KEY)", "INSERT INTO users VALUES (5)");
        LocalUserTableMigrationConfig.migrate(database);
        assertEquals(5, number(database, "SELECT id FROM users"));
    }

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    void refusesAmbiguousTablesWithoutOverwritingAccountsOrForeignKeys(boolean hasLegacyAccount) throws Exception {
        DataSource database = database(true);
        execute(database, "CREATE TABLE \"user\" (id BIGINT PRIMARY KEY)",
                "CREATE TABLE users (id BIGINT PRIMARY KEY)", "INSERT INTO users VALUES (2)",
                "CREATE TABLE bookings (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES \"user\"(id))");
        if (hasLegacyAccount) execute(database, "INSERT INTO \"user\" VALUES (1)", "INSERT INTO bookings VALUES (10, 1)");
        assertThrows(SQLException.class, () -> LocalUserTableMigrationConfig.migrate(database));
        assertEquals(hasLegacyAccount ? 1 : 0, number(database, "SELECT COUNT(*) FROM \"user\""));
        assertEquals(2, number(database, "SELECT id FROM users"));
        assertThrows(SQLException.class, () -> execute(database, "INSERT INTO bookings VALUES (11, 2)"));
    }

    private DataSource database(boolean lowerCase) {
        return new DriverManagerDataSource("jdbc:h2:mem:migration-" + UUID.randomUUID()
                + ";DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=" + lowerCase, "sa", "");
    }

    private void execute(DataSource database, String... sql) throws SQLException {
        try (var connection = database.getConnection(); var statement = connection.createStatement()) {
            for (String command : sql) statement.execute(command);
        }
    }

    private long number(DataSource database, String sql) throws SQLException {
        try (var connection = database.getConnection(); var statement = connection.createStatement();
             var rows = statement.executeQuery(sql)) {
            assertTrue(rows.next());
            return rows.getLong(1);
        }
    }
}
