-- PostgreSQL / Aiven bootstrap for an empty application database.
-- Matches the seven JPA entities on branch nuttachai_673380581-8_04.
-- Run explicitly against the intended database, in one transaction, for example:
--   psql --set=ON_ERROR_STOP=1 --single-transaction --file=schema.sql
-- Supply the connection and SSL settings outside this file; do not store passwords here.
-- After initialization, use spring.jpa.hibernate.ddl-auto=validate and
-- spring.sql.init.mode=never in the deployment environment.
-- This nested resource is not executed by Spring Boot's default schema.sql lookup.
-- Re-running preserves existing rows. IF NOT EXISTS does not migrate old tables
-- whose columns or constraints differ; those changes need a reviewed migration.
-- There are no demo accounts, passwords, seed rows, or destructive table operations.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    active BOOLEAN,
    created_at DATE,
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN', 'STAFF'))
);

CREATE TABLE IF NOT EXISTS user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    phone VARCHAR(255),
    department VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_user_profile_user UNIQUE (user_id),
    CONSTRAINT fk_user_profile_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS meeting_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL,
    floor VARCHAR(20),
    room_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT ck_meeting_rooms_type CHECK (room_type IN ('STANDARD', 'VIP')),
    CONSTRAINT ck_meeting_rooms_status CHECK (status IN ('AVAILABLE', 'MAINTENANCE'))
);

CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    total_quantity INTEGER NOT NULL,
    category VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    start_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    purpose VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES meeting_rooms (id),
    CONSTRAINT ck_bookings_status CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')
    )
);

CREATE TABLE IF NOT EXISTS booking_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_booking_equipment_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_equipment_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
    CONSTRAINT ck_booking_equipment_quantity CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS booking_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    old_status VARCHAR(255),
    new_status VARCHAR(255) NOT NULL,
    changed_by BIGINT,
    changed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_booking_status_history_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_status_history_changed_by FOREIGN KEY (changed_by) REFERENCES users (id),
    CONSTRAINT ck_booking_status_history_old_status CHECK (
        old_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')
    ),
    CONSTRAINT ck_booking_status_history_new_status CHECK (
        new_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')
    )
);

CREATE INDEX IF NOT EXISTS idx_booking_room_time ON bookings (room_id, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_booking_user ON bookings (user_id);
CREATE INDEX IF NOT EXISTS idx_booking_equipment_booking ON booking_equipment (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_equipment_equipment ON booking_equipment (equipment_id);
CREATE INDEX IF NOT EXISTS idx_booking_status_history_booking ON booking_status_history (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_status_history_changed_by ON booking_status_history (changed_by);
